GET http://localhost:3000/blocks

###

POST http://localhost:3000/blocks
Content-type: application/json

{
  "data":"Second block baby!!"
}

###

POST http://localhost:3000/peers
content-type: application/json

{
  "peer":"ws://localhost:4000"
}

###

GET http://localhost:3000/me/balance

###

POST http://localhost:3000/transactions/
content-type: application/json

{
  "address":"04aa8ac72f11754a173db464723d0d06b0961bbba1e8410dd06335acd549dc11d13c4271bf86f92c53279967ef09d995cc3242db4a08b701a2b54e987240e5fd92",
  "amount" : 30
}