GET http://localhost:3000/blocks

###

POST http://localhost:3000/blocks
Content-type: application/json

{
  "data":"Second block baby!!"
}

###

POST http://localhost:3000/peers
content-type: application/json

{
  "peer":"ws://localhost:4000"
}

###

GET http://localhost:3000/me/balance
