GET http://localhost:3000/blocks

###

POST http://localhost:3000/blocks
Content-type: application/json

{
  "data":"Second block baby!!"
}

###

POST http://localhost:3000/peers
content-type: application/json

{
  "peer":"ws://localhost:4000"
}

###

GET http://localhost:3000/me/balance

###

POST http://localhost:3000/transactions/
content-type: application/json

{
  "address":"046fc466fbae488d9aa13c56cbfcd97505f4db555ebf011987447e861cfb29a853112aeeca50228439a4536aae0145f12c088db66b65ad3b1744291ad78e5193a7",
  "amount" : 40
}